services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: budgetops
      POSTGRES_USER: budgetops
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    # dev는 보통 소스에서 빌드(또는 latest 이미지 그대로 사용 가능)
    # build: ./backend
    image: ghcr.io/yyoajung/budgetops-backend:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/budgetops
      SPRING_DATASOURCE_USERNAME: budgetops
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_AUTOCONFIGURE_EXCLUDE:
      SPRING_SQL_INIT_MODE: never

volumes:
  pgdata_dev:
