services:
  app:
    image: ghcr.io/yyoajung/budgetops-backend:latest
    environment:
      SERVER_PORT: "8080"
      # DB 쓸 때는 아래 3개를 .env에서 주입 (dev/prod 파일에서 값만 채움)
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-}
      # ↓ 개발 초기에 DB 비활성화할 때만 사용(운영에서 DB 붙이면 제거)
      SPRING_AUTOCONFIGURE_EXCLUDE: ${SPRING_AUTOCONFIGURE_EXCLUDE:-}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE:-never}
    restart: unless-stopped