name: Claude PR Assistant

on:
  # PR 생성/수정 트리거 (내부 브랜치 기준)
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned, labeled]
  pull_request_review:
    types: [submitted]

concurrency:
  group: claude-pr-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 1) 외부 프롬프트 shallow clone + 복사 (있다면)
      - name: Sync prompts
        run: |
          git clone --depth=1 https://github.com/YYOAJUNG/prompts tmp-prompts
          tmp-prompts/sync.sh tmp-prompts/claude/review/backend .claude/review
          rm -rf tmp-prompts

      # 2) Claude 실행 (라벨 트리거)
      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.CLAUDE_GH_TOKEN }}